"use client";
import { useEffect,useMemo,useState } from "react";
import AppShell from "@/components/AppShell";
import { Badge,Button,Empty,ErrorBox,Field,inputClass,Modal,PageIntro,Panel } from "@/components/v3/Kit";
import { hasPermission } from "@/lib/auth";
import { crmApi,type Client,type Contract,type DocumentTemplate } from "@/lib/crmApi";
const money=(v:string|number|null|undefined)=>v===null||v===undefined?"—":new Intl.NumberFormat("en-US",{maximumFractionDigits:2}).format(Number(v));
const date=(v?:string|null)=>v?new Intl.DateTimeFormat("en",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(v)):"—";
export default function ContractsPage(){
 const [rows,setRows]=useState<Contract[]>([]),[clients,setClients]=useState<Client[]>([]),[templates,setTemplates]=useState<DocumentTemplate[]>([]),[q,setQ]=useState(""),[status,setStatus]=useState(""); const [error,setError]=useState(""),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[saving,setSaving]=useState(false); const [form,setForm]=useState({client_id:"",template_id:"",title:"",amount:"",effective_from:"",effective_until:""});
 const canCreate=hasPermission("contracts.create"),canEdit=hasPermission("contracts.edit"),canDelete=hasPermission("contracts.delete"),canDownload=hasPermission("contracts.download"),canApprove=hasPermission("contracts.approve");
 async function load(){setLoading(true);setError("");try{const [a,b,c]=await Promise.all([crmApi.contracts.list(),crmApi.clients.list().catch(()=>[]),crmApi.templates.list().catch(()=>[])]);setRows(a);setClients(b);setTemplates(c.filter(t=>/contract|nda|agreement/i.test(`${t.category??""} ${t.type??""} ${t.name}`)))}catch(e){setError(e instanceof Error?e.message:"Unable to load contracts")}finally{setLoading(false)}} useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>rows.filter(r=>(!q||`${r.contract_number??""} ${r.title??""} ${r.client?.name??""}`.toLowerCase().includes(q.toLowerCase()))&&(!status||r.status===status)),[rows,q,status]);
 async function create(){if(!form.client_id||!form.template_id||!form.amount)return;setSaving(true);try{await crmApi.contracts.generate({client_id:Number(form.client_id),template_id:Number(form.template_id),title:form.title||undefined,amount:form.amount,effective_from:form.effective_from||undefined,effective_until:form.effective_until||undefined});setOpen(false);setForm({client_id:"",template_id:"",title:"",amount:"",effective_from:"",effective_until:""});await load()}catch(e){setError(e instanceof Error?e.message:"Unable to create contract")}finally{setSaving(false)}}
 async function approve(id:number){try{await crmApi.contracts.approve(id);await load()}catch(e){setError(e instanceof Error?e.message:"Unable to approve contract")}}
 async function remove(id:number){if(!confirm("Delete this contract? This action is permission protected."))return;try{await crmApi.contracts.delete(id);await load()}catch(e){setError(e instanceof Error?e.message:"Unable to delete contract")}}
 return <AppShell title="Contracts" subtitle="Protected agreements accessible only to explicitly authorized roles"><PageIntro eyebrow="Sensitive Business Data" title="Contracts Vault" description="Contracts are isolated behind dedicated permissions. Unauthorized roles cannot see this menu, open contract pages, or query contract APIs." actions={canCreate?<Button onClick={()=>setOpen(true)}>+ Create contract</Button>:undefined}/><ErrorBox message={error}/><div className="mb-5 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800"><b>Protected module:</b> visibility, actions, downloads and API access are independently permission controlled.</div><Panel><div className="flex flex-col gap-3 border-b border-slate-100 p-4 md:flex-row"><input className={inputClass} placeholder="Search contract number, title or client…" value={q} onChange={e=>setQ(e.target.value)}/><select className={`${inputClass} md:max-w-[210px]`} value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option value="generated">Generated</option><option value="approved">Approved</option><option value="archived">Archived</option></select></div>{loading?<div className="py-20 text-center text-sm text-slate-500">Loading protected contracts…</div>:filtered.length?<div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left"><thead className="bg-slate-50 text-[10px] uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-3">Contract</th><th className="px-5 py-3">Client</th><th className="px-5 py-3">Effective</th><th className="px-5 py-3">Amount</th><th className="px-5 py-3">Status</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map(r=><tr key={r.id} className="hover:bg-slate-50/70"><td className="px-5 py-4"><b className="text-sm">{r.title||r.template?.name||"Contract"}</b><div className="mt-0.5 text-xs font-medium text-blue-600">{r.contract_number||`#${r.id}`}</div></td><td className="px-5 py-4 text-sm">{r.client?.name||"—"}</td><td className="px-5 py-4 text-xs text-slate-500">{date(r.effective_from)}<br/>to {date(r.effective_until)}</td><td className="px-5 py-4 text-sm font-semibold">{money(r.amount)}</td><td className="px-5 py-4"><Badge tone={r.status==="approved"?"green":r.status==="archived"?"slate":"blue"}>{r.status||"generated"}</Badge></td><td className="px-5 py-4"><div className="flex justify-end gap-2">{canDownload&&<Button tone="secondary" onClick={()=>crmApi.contracts.download(r.id)}>Download</Button>}{canApprove&&r.status!=="approved"&&<Button onClick={()=>approve(r.id)}>Approve</Button>}{canDelete&&<Button tone="danger" onClick={()=>remove(r.id)}>Delete</Button>}</div></td></tr>)}</tbody></table></div>:<Empty title="No contracts found" body="Create the first authorized contract or adjust your filters."/>}</Panel>
 <Modal open={open} onClose={()=>setOpen(false)} title="Create protected contract" subtitle="Generate an agreement from an approved contract template." footer={<><Button tone="secondary" onClick={()=>setOpen(false)}>Cancel</Button><Button disabled={saving||!form.client_id||!form.template_id||!form.amount} onClick={create}>{saving?"Generating…":"Generate contract"}</Button></>}><div className="grid gap-4 sm:grid-cols-2"><Field label="Client"><select className={inputClass} value={form.client_id} onChange={e=>setForm({...form,client_id:e.target.value})}><option value="">Select client</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Contract template"><select className={inputClass} value={form.template_id} onChange={e=>setForm({...form,template_id:e.target.value})}><option value="">Select template</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></Field><div className="sm:col-span-2"><Field label="Contract title"><input className={inputClass} value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="e.g. Website Development Agreement"/></Field></div><Field label="Amount"><input className={inputClass} inputMode="decimal" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></Field><div/><Field label="Effective from"><input type="date" className={inputClass} value={form.effective_from} onChange={e=>setForm({...form,effective_from:e.target.value})}/></Field><Field label="Effective until"><input type="date" className={inputClass} value={form.effective_until} onChange={e=>setForm({...form,effective_until:e.target.value})}/></Field></div></Modal>
 </AppShell>
}
