"use client";

import React from "react";

export function cx(...v:Array<string|false|null|undefined>){return v.filter(Boolean).join(" ")}
export function Panel({children,className=""}:{children:React.ReactNode;className?:string}){return <section className={cx("rounded-2xl border border-slate-200 bg-white shadow-sm",className)}>{children}</section>}
export function PanelHead({title,subtitle,actions}:{title:string;subtitle?:string;actions?:React.ReactNode}){return <div className="flex flex-col gap-3 border-b border-slate-100 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-bold text-slate-900">{title}</h2>{subtitle&&<p className="mt-0.5 text-xs text-slate-500">{subtitle}</p>}</div>{actions&&<div className="flex flex-wrap gap-2">{actions}</div>}</div>}
export function Button({children,onClick,type="button",tone="primary",disabled,className=""}:{children:React.ReactNode;onClick?:()=>void;type?:"button"|"submit";tone?:"primary"|"secondary"|"danger"|"ghost";disabled?:boolean;className?:string}){const tones={primary:"bg-[#0b2b55] text-white hover:bg-[#123b70]",secondary:"border border-slate-200 bg-white text-slate-700 hover:bg-slate-50",danger:"bg-rose-600 text-white hover:bg-rose-700",ghost:"text-slate-600 hover:bg-slate-100"};return <button type={type} onClick={onClick} disabled={disabled} className={cx("inline-flex h-10 items-center justify-center rounded-xl px-4 text-sm font-semibold disabled:cursor-not-allowed disabled:opacity-50",tones[tone],className)}>{children}</button>}
export function Badge({children,tone="slate"}:{children:React.ReactNode;tone?:"slate"|"blue"|"green"|"amber"|"red"|"violet"}){const t={slate:"bg-slate-100 text-slate-700",blue:"bg-blue-50 text-blue-700",green:"bg-emerald-50 text-emerald-700",amber:"bg-amber-50 text-amber-700",red:"bg-rose-50 text-rose-700",violet:"bg-violet-50 text-violet-700"};return <span className={cx("inline-flex rounded-full px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider",t[tone])}>{children}</span>}
export function Modal({open,onClose,title,subtitle,children,footer}:{open:boolean;onClose:()=>void;title:string;subtitle?:string;children:React.ReactNode;footer?:React.ReactNode}){if(!open)return null;return <div className="fixed inset-0 z-[100] grid place-items-center bg-slate-950/50 p-4 backdrop-blur-sm" onMouseDown={onClose}><div className="max-h-[92vh] w-full max-w-2xl overflow-hidden rounded-3xl border border-white/10 bg-white shadow-2xl" onMouseDown={e=>e.stopPropagation()}><div className="flex items-start justify-between border-b border-slate-100 px-6 py-5"><div><h3 className="text-lg font-bold">{title}</h3>{subtitle&&<p className="mt-1 text-xs text-slate-500">{subtitle}</p>}</div><button onClick={onClose} className="grid h-9 w-9 place-items-center rounded-xl bg-slate-100 text-slate-500 hover:text-slate-900">×</button></div><div className="max-h-[68vh] overflow-y-auto p-6">{children}</div>{footer&&<div className="flex justify-end gap-2 border-t border-slate-100 bg-slate-50/70 px-6 py-4">{footer}</div>}</div></div>}
export function Field({label,children,hint}:{label:string;children:React.ReactNode;hint?:string}){return <label className="block"><span className="mb-1.5 block text-xs font-semibold text-slate-700">{label}</span>{children}{hint&&<span className="mt-1 block text-[11px] text-slate-400">{hint}</span>}</label>}
export const inputClass="h-11 w-full rounded-xl border border-slate-200 bg-white px-3.5 text-sm outline-none placeholder:text-slate-400 focus:border-blue-400 focus:ring-4 focus:ring-blue-50";
export const textareaClass="min-h-28 w-full resize-y rounded-xl border border-slate-200 bg-white px-3.5 py-3 text-sm outline-none placeholder:text-slate-400 focus:border-blue-400 focus:ring-4 focus:ring-blue-50";
export function Empty({title,body}:{title:string;body:string}){return <div className="px-6 py-16 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-slate-100 text-xl">◇</div><h3 className="mt-3 font-semibold">{title}</h3><p className="mx-auto mt-1 max-w-md text-sm text-slate-500">{body}</p></div>}
export function PageIntro({eyebrow,title,description,actions}:{eyebrow?:string;title:string;description:string;actions?:React.ReactNode}){return <div className="mb-6 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div>{eyebrow&&<div className="mb-2 text-[10px] font-bold uppercase tracking-[.2em] text-blue-600">{eyebrow}</div>}<h1 className="text-2xl font-black tracking-tight text-slate-950 sm:text-3xl">{title}</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">{description}</p></div>{actions&&<div className="flex flex-wrap gap-2">{actions}</div>}</div>}
export function ErrorBox({message}:{message:string}){return message?<div className="mb-5 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{message}</div>:null}
