"use client";
import { useEffect,useMemo,useState } from "react";
import AppShell from "@/components/AppShell";
import { Badge,Button,Empty,ErrorBox,Field,inputClass,Modal,PageIntro,Panel,PanelHead } from "@/components/v3/Kit";
import { hasPermission } from "@/lib/auth";
import { crmApi,type PermissionModule,type RoleRecord } from "@/lib/crmApi";
const pretty=(s:string)=>s.replaceAll("_"," ").replaceAll("."," › ").replace(/\b\w/g,m=>m.toUpperCase());
export default function RolesPermissionsPage(){
 const [roles,setRoles]=useState<RoleRecord[]>([]),[modules,setModules]=useState<PermissionModule[]>([]),[selectedId,setSelectedId]=useState<number|null>(null),[draft,setDraft]=useState<string[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[open,setOpen]=useState(false),[newRole,setNewRole]=useState({display_name:"",description:""});
 const canManage=hasPermission("roles.manage");
 async function load(){setLoading(true);setError("");try{const r=await crmApi.roles.list();setRoles(r.roles);setModules(r.modules);const pick=selectedId&&r.roles.some(x=>x.id===selectedId)?selectedId:r.roles[0]?.id??null;setSelectedId(pick);setDraft(r.roles.find(x=>x.id===pick)?.permissions??[])}catch(e){setError(e instanceof Error?e.message:"Unable to load roles")}finally{setLoading(false)}} useEffect(()=>{load()},[]);
 const selected=useMemo(()=>roles.find(r=>r.id===selectedId)??null,[roles,selectedId]);
 function select(r:RoleRecord){setSelectedId(r.id);setDraft([...r.permissions])}
 function toggle(p:string){if(!canManage||selected?.is_system)return;setDraft(d=>d.includes(p)?d.filter(x=>x!==p):[...d,p])}
 function toggleModule(m:PermissionModule){if(!canManage||selected?.is_system)return;const all=m.permissions.every(p=>draft.includes(p));setDraft(d=>all?d.filter(x=>!m.permissions.includes(x)):Array.from(new Set([...d,...m.permissions])))}
 async function save(){if(!selected)return;setSaving(true);try{await crmApi.roles.update(selected.id,{permissions:draft});await load()}catch(e){setError(e instanceof Error?e.message:"Unable to save permissions")}finally{setSaving(false)}}
 async function create(){if(!newRole.display_name.trim())return;setSaving(true);try{await crmApi.roles.create({display_name:newRole.display_name,description:newRole.description,permissions:[]});setOpen(false);setNewRole({display_name:"",description:""});await load()}catch(e){setError(e instanceof Error?e.message:"Unable to create role")}finally{setSaving(false)}}
 async function remove(){if(!selected||selected.is_system||!confirm(`Delete custom role “${selected.display_name}”?`))return;try{await crmApi.roles.delete(selected.id);setSelectedId(null);await load()}catch(e){setError(e instanceof Error?e.message:"Unable to delete role")}}
 return <AppShell title="Roles & Permissions" subtitle="Enterprise RBAC with dynamic custom roles and module-level CRUD control"><PageIntro eyebrow="Access Governance" title="Roles & Permission Center" description="Permissions are the source of authority — not hard-coded role names. Administrators can create future roles, grant module actions and protect sensitive business data without changing code." actions={canManage?<Button onClick={()=>setOpen(true)}>+ Create custom role</Button>:undefined}/><ErrorBox message={error}/>
 <div className="grid gap-6 xl:grid-cols-[320px_1fr]"><Panel><PanelHead title="Roles" subtitle={`${roles.length} configured roles`}/><div className="max-h-[70vh] overflow-auto p-2">{loading?<div className="p-8 text-center text-sm text-slate-500">Loading…</div>:roles.map(r=><button key={r.id} onClick={()=>select(r)} className={`mb-1 w-full rounded-xl border p-3 text-left transition ${selectedId===r.id?"border-blue-200 bg-blue-50":"border-transparent hover:bg-slate-50"}`}><div className="flex items-center justify-between gap-2"><b className="truncate text-sm">{r.display_name}</b>{r.is_system?<Badge tone="violet">System</Badge>:<Badge>{r.users_count} users</Badge>}</div><p className="mt-1 line-clamp-2 text-[11px] leading-4 text-slate-500">{r.description||"Configurable CRM role"}</p></button>)}</div></Panel>
 <Panel>{selected?<><PanelHead title={selected.display_name} subtitle={`${draft.length} permissions enabled`} actions={<>{!selected.is_system&&canManage&&<Button tone="secondary" onClick={remove}>Delete role</Button>}{canManage&&<Button disabled={saving||selected.is_system} onClick={save}>{selected.is_system?"Protected role":saving?"Saving…":"Save permissions"}</Button>}</>}/>{selected.is_system&&<div className="m-5 rounded-xl border border-violet-200 bg-violet-50 px-4 py-3 text-sm text-violet-800"><b>Protected system role.</b> Full System Administrator permissions cannot be accidentally reduced.</div>}<div className="grid gap-4 p-5 2xl:grid-cols-2">{modules.map(m=>{const enabled=m.permissions.filter(p=>draft.includes(p)).length;const all=enabled===m.permissions.length;return <div key={m.module} className="overflow-hidden rounded-2xl border border-slate-200"><div className="flex items-center justify-between bg-slate-50 px-4 py-3"><div><b className="text-sm">{m.label}</b><div className="text-[10px] uppercase tracking-wider text-slate-400">{enabled}/{m.permissions.length} enabled</div></div><button disabled={!canManage||selected.is_system} onClick={()=>toggleModule(m)} className={`h-7 rounded-full px-3 text-[10px] font-bold uppercase tracking-wider ${all?"bg-emerald-100 text-emerald-700":"bg-white text-slate-500 border border-slate-200"}`}>{all?"All on":"Enable all"}</button></div><div className="divide-y divide-slate-100">{m.permissions.map(p=><label key={p} className="flex cursor-pointer items-center justify-between gap-4 px-4 py-3 hover:bg-slate-50"><div><div className="text-sm font-medium">{pretty(p.split(".").slice(1).join("."))}</div><code className="text-[10px] text-slate-400">{p}</code></div><input type="checkbox" checked={draft.includes(p)} disabled={!canManage||selected.is_system} onChange={()=>toggle(p)} className="h-4 w-4 accent-blue-600"/></label>)}</div></div>})}</div></>:<Empty title="Select a role" body="Choose a role to review its permission matrix."/>}</Panel></div>
 <Modal open={open} onClose={()=>setOpen(false)} title="Create custom role" subtitle="Create a future-proof role and then assign its permissions." footer={<><Button tone="secondary" onClick={()=>setOpen(false)}>Cancel</Button><Button disabled={saving||!newRole.display_name.trim()} onClick={create}>{saving?"Creating…":"Create role"}</Button></>}><div className="space-y-4"><Field label="Role display name"><input className={inputClass} value={newRole.display_name} onChange={e=>setNewRole({...newRole,display_name:e.target.value})} placeholder="e.g. QA Engineer"/></Field><Field label="Description"><textarea className="min-h-28 w-full rounded-xl border border-slate-200 p-3 text-sm" value={newRole.description} onChange={e=>setNewRole({...newRole,description:e.target.value})} placeholder="What does this role do?"/></Field><div className="rounded-xl bg-blue-50 p-4 text-xs leading-5 text-blue-800">After creation, select the role and enable only the permissions necessary for the job. This keeps least-privilege access scalable for future departments.</div></div></Modal>
 </AppShell>
}
